[package]
name = "flux-config"
version = "0.1.0"

edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { version = "0.13", features = ["toml"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

[lints]
workspace = true
