[package]
authors = ["The Liquid Rust Project Developers"]
edition = "2018"
name = "liquid-rust-typeck"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
liquid-rust-common = { path = "../liquid-rust-common" }
liquid-rust-fixpoint = { path = "../liquid-rust-fixpoint" }
liquid-rust-lrir = { path = "../liquid-rust-lrir" }

rustc-workspace-hack = "1.0.0"

[package.metadata.rust-analyzer]
rustc_private = true
